version: 0.0
os: linux
files:
  - source: /build/libs/holamundo-codedeploy.war
    destination: /opt/tomcat/webapps/holamundo.war
hooks:
  ApplicationStop:
    - location: codedeploy-scripts/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: codedeploy-scripts/beforeinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy-scripts/start.sh
      timeout: 300
      runas: root