version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
hooks:
  ApplicationStop:
    - location: codedeploy-scripts/stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy-scripts/start.sh
      timeout: 300
      runas: root
